apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gunn-data
  namespace: gunn
  labels:
    app.kubernetes.io/name: gunn
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
