name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'

      - name: Sync documentation dependencies
        run: uv sync --group docs
        env:
          UV_CACHE_DIR: .uv-cache

      - name: Generate API reference
        run: uv run sphinx-apidoc -o docs/api src/gunn
        env:
          UV_CACHE_DIR: .uv-cache

      - name: Build Sphinx site
        run: uv run sphinx-build -b html docs docs/_build/html
        env:
          UV_CACHE_DIR: .uv-cache

      - name: Prepare Pages artifact
        run: |
          touch docs/_build/html/.nojekyll
        env:
          UV_CACHE_DIR: .uv-cache

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
